name: portal
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  flutter_animate: ^4.3.0
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.5.0
  firebase_auth_web: ^5.8.13
  file_picker: ^6.1.1
  js: ^0.7.1
  intl: ^0.18.1
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.2
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/Nasawa.png
  uses-material-design: true