// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnjLqhG_K8aWF7QgOLFKq5I0L-zuwAyn4',
    appId: '1:286125361384:web:9c8943fc4cf3266c23215d',
    messagingSenderId: '286125361384',
    projectId: 'studentportal-49d00',
    authDomain: 'studentportal-49d00.firebaseapp.com',
    storageBucket: 'studentportal-49d00.firebasestorage.app',
    measurementId: 'G-N3BZ5DTNLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX1AXZZ7CbkDckVspXqL9I7rpn5Uu551I',
    appId: '1:286125361384:android:9d4fbf7a06c9b96323215d',
    messagingSenderId: '286125361384',
    projectId: 'studentportal-49d00',
    storageBucket: 'studentportal-49d00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkrgt2wPxZnCHVbVgEFRxs9HsycgH8s7I',
    appId: '1:286125361384:ios:ce0870cac4fde7a823215d',
    messagingSenderId: '286125361384',
    projectId: 'studentportal-49d00',
    storageBucket: 'studentportal-49d00.firebasestorage.app',
    iosBundleId: 'com.example.portal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkrgt2wPxZnCHVbVgEFRxs9HsycgH8s7I',
    appId: '1:286125361384:ios:ce0870cac4fde7a823215d',
    messagingSenderId: '286125361384',
    projectId: 'studentportal-49d00',
    storageBucket: 'studentportal-49d00.firebasestorage.app',
    iosBundleId: 'com.example.portal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX1AXZZ7CbkDckVspXqL9I7rpn5Uu551I',
    appId: '1:286125361384:windows:9d4fbf7a06c9b96323215d',
    messagingSenderId: '286125361384',
    projectId: 'studentportal-49d00',
    storageBucket: 'studentportal-49d00.firebasestorage.app',
  );
}
